//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaseosEcologicos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Clientes1 = new HashSet<Clientes>();
            this.Reservaciones = new HashSet<Reservaciones>();
            this.Servicios_Consumidos = new HashSet<Servicios_Consumidos>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AfiliadorId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
    
        public virtual ICollection<Clientes> Clientes1 { get; set; }
        public virtual Clientes Clientes2 { get; set; }
        public virtual ICollection<Reservaciones> Reservaciones { get; set; }
        public virtual ICollection<Servicios_Consumidos> Servicios_Consumidos { get; set; }
    }
}
