//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaseosEcologicos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaseosEcologicosEntities : DbContext
    {
        public PaseosEcologicosEntities()
            : base("name=PaseosEcologicosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Implementos> Implementos { get; set; }
        public DbSet<Paseos> Paseos { get; set; }
        public DbSet<Reservaciones> Reservaciones { get; set; }
        public DbSet<Servicios> Servicios { get; set; }
        public DbSet<Servicios_Consumidos> Servicios_Consumidos { get; set; }
        public DbSet<Tipos_De_Servicios> Tipos_De_Servicios { get; set; }
    }
}
