//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaseosEcologicos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paseos
    {
        public Paseos()
        {
            this.Reservaciones = new HashSet<Reservaciones>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaDePartida { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual ICollection<Reservaciones> Reservaciones { get; set; }
    }
}
