//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaseosEcologicos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservaciones
    {
        public Reservaciones()
        {
            this.Servicios_Consumidos = new HashSet<Servicios_Consumidos>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> PaseoId { get; set; }
        public Nullable<int> Cantidad_De_Personas { get; set; }
        public string Codigo_Verificacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Paseos Paseos { get; set; }
        public virtual ICollection<Servicios_Consumidos> Servicios_Consumidos { get; set; }
    }
}
