//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaseosEcologicos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios_Consumidos
    {
        public int Id { get; set; }
        public Nullable<int> ReservacionId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> ServicioId { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Reservaciones Reservaciones { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
