//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaseosEcologicos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReporteDeCosumo
    {
        public Nullable<int> ReservacionId { get; set; }
        public Nullable<int> PaseoId { get; set; }
        public string TituloDePaseo { get; set; }
        public int ClienteId { get; set; }
        public string Cliente { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public Nullable<int> RepresentateId { get; set; }
        public string Representante { get; set; }
        public string TelRepresentante { get; set; }
        public string CorreoRepresentante { get; set; }
        public Nullable<int> ServicioId { get; set; }
        public string TipoDeServicio { get; set; }
        public string ServicioConsumido { get; set; }
        public Nullable<decimal> PrecioDeServicioConsumido { get; set; }
    }
}
